# WhiteWash

## Using Python's List
First version using Python's list. Note that because of _aliasing_, the general way of copying a 2D list correctly is to use `deepcopy` from `copy` module, otherwise you will change the original color map rather than the new one:

In [1]:
import copy

def WhiteWash(ColorMap):
    """white wash color map as a Pyhton's list"""
    r = copy.deepcopy(ColorMap)
    for c in r:
        for i in range(3):
            c[i] += 1.0
            c[i] *= 0.5
    return r

# testing our function
cm = [[0, 0, 0], [0.1, 0.1, 0.1], [0.5, 0.5, 0.5], [1, 1, 1]]
print("before:", cm)
print("after: ", WhiteWash(cm))

before: [[0, 0, 0], [0.1, 0.1, 0.1], [0.5, 0.5, 0.5], [1, 1, 1]]
after:  [[0.5, 0.5, 0.5], [0.55, 0.55, 0.55], [0.75, 0.75, 0.75], [1.0, 1.0, 1.0]]


## Using `NumPy`'s Arrays

In [2]:
import numpy as np

def NpWhiteWash(ColorMap):
    """white wash color map as a numpy's array"""
    r =  np.ones_like(ColorMap)
    r += ColorMap
    r *= 0.5
    return r

In [3]:
cm = np.random.random(30).reshape((10, 3))

# both functions should return the same result
assert (WhiteWash(cm) == NpWhiteWash(cm)).all()

print("before white wash:")
print(cm)
print("\nafter white wash:")
print(WhiteWash(cm))
print("\nafter white wash with numpy:")
print(NpWhiteWash(cm))

before white wash:
[[ 0.82977558  0.72058037  0.17773973]
 [ 0.13493529  0.12950474  0.96475657]
 [ 0.50937435  0.3089535   0.21655294]
 [ 0.65685957  0.87916125  0.99851318]
 [ 0.07723225  0.48620249  0.42696668]
 [ 0.44156967  0.00612573  0.79058116]
 [ 0.64160115  0.43803504  0.09439299]
 [ 0.486109    0.27711707  0.63857267]
 [ 0.38460828  0.53043106  0.58268727]
 [ 0.73586202  0.73172075  0.48056991]]

after white wash:
[[ 0.91488779  0.86029019  0.58886986]
 [ 0.56746764  0.56475237  0.98237828]
 [ 0.75468717  0.65447675  0.60827647]
 [ 0.82842979  0.93958063  0.99925659]
 [ 0.53861613  0.74310124  0.71348334]
 [ 0.72078484  0.50306287  0.89529058]
 [ 0.82080057  0.71901752  0.5471965 ]
 [ 0.7430545   0.63855853  0.81928633]
 [ 0.69230414  0.76521553  0.79134363]
 [ 0.86793101  0.86586037  0.74028496]]

after white wash with numpy:
[[ 0.91488779  0.86029019  0.58886986]
 [ 0.56746764  0.56475237  0.98237828]
 [ 0.75468717  0.65447675  0.60827647]
 [ 0.82842979  0.93958063  0.9992