In [15]:
#Alex Ly
#100548033

import numpy as np

def WhiteWash(array,num):
    newArray=np.ndarray(shape=array.shape,dtype=float) # new array with same shape as old array
    for i in range(0,num):
        for j in range (0,3):
            newArray[i][j]=(array[i][j]+1)/2# average of value with 1 (white)
    return newArray

np.random.seed(100)
num=np.random.randint(1,100)# random number of rows
array=np.ndarray(shape=(num,3),dtype=int)
for i in range (0,num):
    for j in range (0,3):
        array[i][j]=np.random.randint(0,2)# 0 or 1
print("Original matrix")
print(array)        
newArray=WhiteWash(array,num)
print("New matrix")
print(newArray)

Original matrix
[[0 1 1]
 [1 1 0]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [1 0 0]
 [1 0 1]
 [0 0 0]
 [1 1 1]]
New matrix
[[ 0.5  1.   1. ]
 [ 1.   1.   0.5]
 [ 0.5  0.5  0.5]
 [ 0.5  1.   0.5]
 [ 0.5  0.5  0.5]
 [ 1.   0.5  0.5]
 [ 1.   0.5  1. ]
 [ 0.5  0.5  0.5]
 [ 1.   1.   1. ]]
